#!/bin/bash
if [ "$EUID" -ne 0 ]
	then echo "Please run as root"
	exit
fi

if command -v python3 &>/dev/null; then
    echo "Python 3 is installed"
else
    echo "Python 3 is not installed, please install before continuing."
fi

apt-get update
apt-get install exfat-fuse exfat-utils ntfs-3g -y
mkdir /media/exfat

cp backupX.service /lib/systemd/system/backupX.service
sed -i -e 's?%pwd%?'`pwd`'?' /lib/systemd/system/backupX.service

sudo systemctl daemon-reload

if [ $? -ne 0 ]; then
	exit
fi

sudo systemctl enable backupX.service

if [ $? -eq 0 ]; then
	sudo reboot
fi
